-- Modelo de datos del Módulo 1: PERSONA, POLIZA, RIESGO, IPC y AVISO.
-- El endoso vive en las columnas de POLIZA y RIESGO (no hay tabla de endosos):
--   POLIZA: una fila por endoso; la de mayor num_endoso es la póliza vigente.
--   RIESGO: en cada endoso solo se escriben los riesgos que cambian; la fila actual de cada riesgo tiene vigente = 'S'.
-- AVISO es el outbox: se guarda en la misma transacción que el endoso y el procesador de avisos lo entrega después.

CREATE TABLE persona (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) NOT NULL,
    tipo_documento    VARCHAR(5)     NOT NULL,
    numero_documento  VARCHAR(20)    NOT NULL,
    nombre            VARCHAR(120)   NOT NULL,
    correo            VARCHAR(120),
    celular           VARCHAR(20),
    CONSTRAINT pk_persona PRIMARY KEY (id),
    CONSTRAINT uk_persona_documento UNIQUE (tipo_documento, numero_documento)
);

CREATE TABLE ipc (
    anio        INT            NOT NULL,
    porcentaje  DECIMAL(5, 2)  NOT NULL,
    CONSTRAINT pk_ipc PRIMARY KEY (anio)
);

CREATE SEQUENCE seq_poliza START WITH 2001;
CREATE SEQUENCE seq_riesgo START WITH 101;

CREATE TABLE poliza (
    poliza_id          BIGINT         NOT NULL,
    num_endoso         INT            NOT NULL,
    numero_poliza      VARCHAR(20)    NOT NULL,
    -- Número de la póliza en el CORE: lo asigna el CORE al registrarla (el mock del Módulo 2 no lo devuelve).
    numero_core        VARCHAR(30),
    tipo               VARCHAR(12)    NOT NULL,
    estado             VARCHAR(12)    NOT NULL,
    tipo_endoso        VARCHAR(15)    NOT NULL,
    clase_movimiento   VARCHAR(15)    NOT NULL,
    inicio_vigencia    DATE           NOT NULL,
    fin_vigencia       DATE           NOT NULL,
    meses_vigencia     INT            NOT NULL,
    fecha_endoso       DATE           NOT NULL,
    tomador_id         BIGINT         NOT NULL,
    canon              DECIMAL(15, 2) NOT NULL,
    prima              DECIMAL(15, 2) NOT NULL,
    prima_endoso       DECIMAL(15, 2) NOT NULL,
    -- Origen del endoso: lo que llegó en el bloque "proceso" de la petición.
    canal              VARCHAR(30),
    usuario            VARCHAR(60),
    motivo             VARCHAR(200),
    CONSTRAINT pk_poliza PRIMARY KEY (poliza_id, num_endoso),
    CONSTRAINT fk_poliza_tomador FOREIGN KEY (tomador_id) REFERENCES persona (id),
    CONSTRAINT ck_poliza_tipo CHECK (tipo IN ('INDIVIDUAL', 'COLECTIVA')),
    CONSTRAINT ck_poliza_estado CHECK (estado IN ('VIGENTE', 'RENOVADA', 'CANCELADA')),
    CONSTRAINT ck_poliza_tipo_endoso CHECK (tipo_endoso IN
        ('EMISION', 'INCLUSION', 'EXCLUSION', 'MODIFICACION', 'RENOVACION', 'CANCELACION')),
    CONSTRAINT ck_poliza_clase CHECK (clase_movimiento IN ('COBRO', 'DEVOLUCION', 'SIN_MOVIMIENTO'))
);

CREATE INDEX ix_poliza_tipo_estado ON poliza (tipo, estado);
CREATE INDEX ix_poliza_fin_vigencia ON poliza (fin_vigencia);

-- riesgo_id identifica al riesgo en el API (/riesgos/{id}) y es el mismo en todas sus filas;
-- la llave del modelo sigue siendo (poliza_id, num_endoso, cod_riesgo).
CREATE TABLE riesgo (
    poliza_id           BIGINT         NOT NULL,
    num_endoso          INT            NOT NULL,
    cod_riesgo          INT            NOT NULL,
    riesgo_id           BIGINT         NOT NULL,
    arrendatario_id     BIGINT         NOT NULL,
    arrendador_id       BIGINT         NOT NULL,
    inmueble_direccion  VARCHAR(150)   NOT NULL,
    inmueble_ciudad     VARCHAR(60)    NOT NULL,
    canon_mensual       DECIMAL(15, 2) NOT NULL,
    prima               DECIMAL(15, 2) NOT NULL,
    prima_endoso        DECIMAL(15, 2) NOT NULL,
    fecha_inclusion     DATE           NOT NULL,
    fecha_exclusion     DATE,
    estado              VARCHAR(10)    NOT NULL,
    vigente             VARCHAR(1)     NOT NULL,
    CONSTRAINT pk_riesgo PRIMARY KEY (poliza_id, num_endoso, cod_riesgo),
    CONSTRAINT fk_riesgo_poliza FOREIGN KEY (poliza_id, num_endoso) REFERENCES poliza (poliza_id, num_endoso),
    CONSTRAINT fk_riesgo_arrendatario FOREIGN KEY (arrendatario_id) REFERENCES persona (id),
    CONSTRAINT fk_riesgo_arrendador FOREIGN KEY (arrendador_id) REFERENCES persona (id),
    CONSTRAINT ck_riesgo_estado CHECK (estado IN ('ACTIVO', 'CANCELADO')),
    CONSTRAINT ck_riesgo_vigente CHECK (vigente IN ('S', 'N'))
);

CREATE INDEX ix_riesgo_vigente ON riesgo (poliza_id, vigente);
CREATE INDEX ix_riesgo_id ON riesgo (riesgo_id, vigente);

-- Outbox: un aviso al CORE por cada endoso y, en la emisión y la renovación, otro para el Servicio de Notificaciones.
CREATE TABLE aviso (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) NOT NULL,
    poliza_id     BIGINT         NOT NULL,
    num_endoso    INT            NOT NULL,
    destino       VARCHAR(15)    NOT NULL,
    evento        VARCHAR(30)    NOT NULL,
    estado        VARCHAR(15)    NOT NULL,
    intentos      INT            NOT NULL,
    ultimo_error  VARCHAR(500),
    fecha         TIMESTAMP      NOT NULL,
    CONSTRAINT pk_aviso PRIMARY KEY (id),
    CONSTRAINT fk_aviso_poliza FOREIGN KEY (poliza_id, num_endoso) REFERENCES poliza (poliza_id, num_endoso),
    CONSTRAINT ck_aviso_destino CHECK (destino IN ('CORE', 'NOTIFICACION')),
    CONSTRAINT ck_aviso_estado CHECK (estado IN ('PENDIENTE', 'SINCRONIZADO', 'RECHAZADO'))
);

CREATE INDEX ix_aviso_estado ON aviso (estado, poliza_id, num_endoso);
